# Generated by Django 3.2.6 on 2021-09-19 17:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
